[package]
name = "create_control_object-aux2"
version = "0.2.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "create_control_object_aux2"

[dependencies]
aviutl2 = "0.44.0"
process_path = "0.1.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_UI_Controls",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
