[package]
name = "create_control_object-aux2"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "create_control_object_aux2"

[dependencies]
aviutl2 = "0.44.0"
aviutl2-eframe = "0.44.0"
windows = { version = "0.62.2", features = ["Win32_System_Diagnostics_Debug", "Win32_UI_WindowsAndMessaging"] }
